version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: facturacion-db
    environment:
      POSTGRES_USER: facturacion
      POSTGRES_PASSWORD: facturacion123
      POSTGRES_DB: facturacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10-alpine
    container_name: facturacion-nats
    ports:
      - "4222:4222"

volumes:
  postgres_data: