version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: facturacion-db
    environment:
      POSTGRES_USER: facturacion
      POSTGRES_PASSWORD: facturacion123
      POSTGRES_DB: facturacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: facturacion-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: